travis:
  secure:
    BINSTAR_TOKEN: m1UUvj037lg332ZrwSpI+Qfv68c7V0ekuEE9aHtVwebkxV24WFFqxVFxjmRN1ADJ8JA7EFhc/qVC03YL4a7LOaUPcp9s+XA0EIfi8v47haBpeZ+Hc4Ls6VwLXeXyvKmSHLlG4UFKQ1GXlQTiiZEVytgAaG28VJbRTZMxHAbCtO887o0jPfMgxkZFTARH0Go8jx0AX4pOG07t9mo1y/QGJdAl+icQO2BaL+tfAK7SKezSNQIDNJEViAfa0I9Zhwu+EsTQowWZ40eLoSTgSHxXFYmhSwyPrexptCG9WXHj6BXHO+GZfeVZ52JXdu4UGlPYzAnxhVrXCC4NuQJh0tERwtjCEM8nbB7eLicRBmAZLFc8p2OZCul12dfV11u9bN1UtGTsEIwMdP0iZeanVon2yXZGYXYk+g+Im0NNaNmhhWM7gNrARFnUdLHb1xH3QdRYABSTxTqDrwTALoIDQ7zDnLSQcOI16CVHTdz0oXwPGeB2WDOrnoL2ZWaLzXB24XS7olOg/n4VTdNYoOUEdakhn6YQ8tEI3IFaBIOCOy8PQsF337gTdyhkt5hCz59eCHFSMFayz8bijd2qCXtqDWJcUxbzCSDsFxnQYMnnORl6dIIA7DH6Tiy/liwNRnHA+NIhbZFcdRPOtnBuEeuHtlW2esuWmyTMQtmUCzilQySLEXM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
